-- ✒️ **Ejercicio hecho por Alejandro Montes Delgado con asistencia de Paco Diz Ureña**

--Realiza los módulos de programación necesarios para garantizar que el número de
--auxiliares de vuelo en un viaje es de al menos uno por cada 5 pasajeros que realizan
--ese viaje.

CREATE OR REPLACE PACKAGE PA_TEMP_AUXILIAR
AS
    TYPE R_SAVE_AUX IS RECORD (
        NUMPASAPORTE AUXILIARESDEVIAJE.NUMPASAPORTE%TYPE,
        CODVUELO AUXILIARESDEVIAJE.CODVUELO%TYPE,
        FECHA AUXILIARESDEVIAJE.FECHA%TYPE
    );
    TYPE TR_SAVE_AUX IS TABLE OF R_SAVE_AUX
    INDEX BY BINARY_INTEGER;
    DATOS_AUXILIAR TR_SAVE_AUX;
END;
/

--AHORA CON UN TRIGGER TENEMOS QUE RELLENAR LA TABLA TEMPORAL.
CREATE OR REPLACE TRIGGER T_RELLENA_AUX
BEFORE INSERT OR UPDATE OR DELETE ON AUXILIARESDEVIAJE
DECLARE
    CURSOR C_DATOS IS 
    SELECT *
    FROM AUXILIARESDEVIAJE;
    V_INDICE NUMBER :=0;
BEGIN
    FOR V_DATOS IN C_DATOS LOOP
        PA_TEMP_AUXILIAR.DATOS_AUXILIAR(V_INDICE).NUMPASAPORTE := V_DATOS.NUMPASAPORTE;
        PA_TEMP_AUXILIAR.DATOS_AUXILIAR(V_INDICE).CODVUELO := V_DATOS.CODVUELO;
        PA_TEMP_AUXILIAR.DATOS_AUXILIAR(V_INDICE).FECHA := V_DATOS.FECHA;
        V_INDICE := V_INDICE + 1;
    END LOOP;
END;
/

--PROCEDIMIENTO PRINCIPAL

--FUNCIONAMIENTO LÓGICO.

--ES UN PROCEDIMIENTO Y DESDE DOS TRIGGERS LLAMO AL PROCEDIMIENTO PARA QUE SE EJECUTE CUANDO
--SE ACTUALICE O INSERTE EN LAS TABLAS AUXILIARESDEVIAJE O PASAJEROSEMBARCADOS.

--PRIMERO ABRO EL CURSOR Y LO RECORRO, CON EL WHILE INICIO EL RECORRIDO DE LA TABLA TEMPORAL. 
--COMPARO SI EL PRIMER CODVUELO DEL CURSOR ES IGUAL AL PRIMER CODVUELO DE LA TABLA TEMPORAL. 
--SI ES ASÍ EL CONTADOR SUBE 1 UNA VEZ TERMINE EL WHILE DE COMPARAR, COGEMOS LA VARIABLE V_CONTAUX 
--Y LA COMPARAMOS CON EL NUMERO DE PASAJEROS QUE SE GUARDA EN EL CURSOR, SI DIVIDIMOS EL NUMERO DE 
--PASAJEROS DEL VUELO ENTRE LOS AUXILIARES TIENE QUE SER > 5 Y SALTA UN RAISE APLICATION ERROR.
--CUANDO TERMINE DE RECORRER EL CURSOR TENEMOS QUE PONERLO A 0 NUEVAMENTE Y PASARÁ A COMPARAR EL 
--SIGUIENTE DATO DEL CURSOR.

CREATE OR REPLACE PROCEDURE P_COMPROBAR
IS
    V_INICIO PLS_INTEGER;
    V_DATOS PA_TEMP_AUXILIAR.TR_SAVE_AUX;
    V_CONTAUX NUMBER :=0;
    V_PASAJEROS NUMBER :=0;
    CURSOR C_PASAJEROS IS 
    SELECT COUNT(*) AS "NUMPASAJEROS", CODVUELO
    FROM PASAJEROSEMBARCADOS GROUP BY CODVUELO;
BEGIN
    FOR V_NUM IN C_PASAJEROS LOOP
        V_INICIO := PA_TEMP_AUXILIAR.DATOS_AUXILIAR.FIRST();
        V_DATOS := PA_TEMP_AUXILIAR.DATOS_AUXILIAR;
        WHILE V_INICIO IS NOT NULL LOOP
            IF V_DATOS(V_INICIO).CODVUELO = V_NUM.CODVUELO THEN
                V_CONTAUX := V_CONTAUX +1;
            END IF;
            V_INICIO := V_DATOS.NEXT(V_INICIO);
        END LOOP;
            IF V_CONTAUX != 0 THEN
                IF V_NUM.NUMPASAJEROS/V_CONTAUX > 5 THEN
                    RAISE_APPLICATION_ERROR(-20202,'ERROR. DEBE DE HABER UN AUXILIAR DE VUELO POR CADA 5 PASAJEROS.');
                END IF;
            END IF;
        V_CONTAUX := 0;
    END LOOP;
END;
/



CREATE OR REPLACE TRIGGER T_COMPRUEBA_AUX
BEFORE INSERT OR UPDATE ON AUXILIARESDEVIAJE
FOR EACH ROW
DECLARE

BEGIN
    P_COMPROBAR;
END;
/

CREATE OR REPLACE TRIGGER T_COMPRUEBA_PASAJEROS
BEFORE INSERT OR UPDATE ON PASAJEROSEMBARCADOS
FOR EACH ROW
DECLARE

BEGIN
    P_COMPROBAR;
END;
/


--ESTOS SON LOS INSERT PARA HACER PRUEBAS.
--PARA AÑADIR PASAJEROSEMBARCADOS, PRIMERO TENEMOS QUE AÑADIR LOS PASAJEROS NORMALES. 
--DEJO ALREDEDOR DE 20 INSERTS Y DELETES DE LAS TABLAS PASAJEROS Y PASAJEROSEMBARCADOS.

INSERT INTO AUXILIARES VALUES (
    'HYJ000568'
);

INSERT INTO AUXILIARESDEVIAJE VALUES (
    'HYJ000568',
    'VY-3924',
     TO_DATE('26/09/16','DD/MM/YY')
);

DELETE FROM AUXILIARESDEVIAJE WHERE NUMPASAPORTE = 'HYJ000568';

INSERT INTO PASAJEROS VALUES (
    'JYN000223',
    'Manolo AA'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000224',
    'Manolo AAA'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000225',
    'Manolo AAAA'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000226',
    'Manolo AAAAA'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000227',
    'Manolo AAAAAA'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000228',
    'Manolo AAAAAAA'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000229',
    'Manolo A AAAAAAA'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000210',
    'Manolo AAAAAAAAAA'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000211',
    'Manolo AAAAAAAAAAAAA'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000212',
    'Manolo AAAAAAAC'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000213',
    'Manolo  AAAAAAA'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000214',
    'Manolo AAAAAAA'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000215',
    'Manolo AAAAAAAAAA'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000216',
    'Manolo AAAAAAA'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000217',
    'Manolo SDSDS'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000218',
    'Manolo SSDSDWWW'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000219',
    'Manolo VVVCD'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000220',
    'Manolo  WWWCCC'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000230',
    'Manolo WEEWE'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000231',
    'Manolo VVVVVVVV'
);
INSERT INTO PASAJEROS VALUES (
    'JYN000232',
    'Manolo QQQQQQ'
);

DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000223';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000224';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000225';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000226';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000227';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000228';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000229';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000210';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000211';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000212';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000213';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000214';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000215';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000216';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000217';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000218';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000219';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000220';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000230';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000231';
DELETE FROM PASAJEROS WHERE NUMPASAPORTE = 'JYN000232';

INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000223',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000224',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000225',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000227',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);

INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000228',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000229',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000210',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000211',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000212',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000213',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000214',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000216',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000217',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000218',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000219',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000220',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000230',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000231',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);
INSERT INTO PASAJEROSEMBARCADOS VALUES (
    'JYN000232',
    'IB-3949',
    TO_DATE('26/09/16','DD/MM/YY'),
    0,
    0
);

DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000223';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000224';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000225';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000226';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000227';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000228';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000229';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000210';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000211';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000212';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000213';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000214';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000215';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000216';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000217';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000218';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000219';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000220';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000230';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000231';
DELETE FROM PASAJEROSEMBARCADOS WHERE NUMPASAPORTE = 'JYN000232';
