-- ✒️ **Ejercicio hecho por Alejandro Montes Delgado con asistencia de Juan Jesús Alejo Sillero**

--EJERCICIO3

--Añade dos columnas llamadas Distancia y Duración (en formato hh:mi) a la tabla
--Vuelos y rellénalas adecuadamente. Realiza un trigger que garantice que un avión
--asignado a un viaje tenga una autonomía superior al menos en un 25% a la distancia
--a recorrer.

--MODIFICAR LA TABLA
ALTER TABLE VUELOS ADD DISTANCIA NUMBER(15,2);
ALTER TABLE VUELOS ADD DURACION DATE;
-- ACTUALIZADA LAS NUEVAS COLUMNAS
UPDATE VUELOS SET DISTANCIA=397, DURACION=TO_DATE('1:00','HH24:MI') WHERE CODVUELO='IB-3949';
UPDATE VUELOS SET DISTANCIA=810.30, DURACION=TO_DATE('1:30','HH24:MI') WHERE CODVUELO='IB-5940';
UPDATE VUELOS SET DISTANCIA=203, DURACION=TO_DATE('0:52','HH24:MI') WHERE CODVUELO='VY-3924';
UPDATE VUELOS SET DISTANCIA=859, DURACION=TO_DATE('2:00','HH24:MI') WHERE CODVUELO='AF-1149';
UPDATE VUELOS SET DISTANCIA=2245, DURACION=TO_DATE('3:25','HH24:MI') WHERE CODVUELO='QR-3776';
UPDATE VUELOS SET DISTANCIA=555.99, DURACION=TO_DATE('1:11','HH24:MI') WHERE CODVUELO='UX-6013';


-- EL TRIGGER CONSULTA LA AUTONOMIA DEL AVION NUEVO QUE INSERTEMOS EN LA TABLA VIAJES. 
--NOS ASEGURAMOS QUE LA DISTANCIA MAS UN 25% ES MAYOR QUE LA AUTONOMÍA DEL AVIÓN.

CREATE OR REPLACE TRIGGER T_AUTONOMIA
BEFORE INSERT OR UPDATE ON VUELOS
FOR EACH ROW
DECLARE
    VN_AUTONOMIA MODELOS.AUTONOMIA%TYPE;
BEGIN
    SELECT AUTONOMIA INTO VN_AUTONOMIA
    FROM MODELOS
    WHERE NOMBRE IN ( SELECT NOMBREMODELO
                      FROM AERONAVES
                      WHERE NUMSERIE IN ( SELECT NUMSERIEAERONAVE
                                          FROM VIAJES 
                                          WHERE CODVUELO = :NEW.CODVUELO ) );
    IF :NEW.DISTANCIA * 1.25 > VN_AUTONOMIA THEN
        RAISE_APPLICATION_ERROR(-20002,'El avión no tiene suficiente autonomía para el viaje.');
    END IF;
END;
/

--TENEMOS QUE ASIGNARLE UN AVIÓN SI NO VA A DAR FALLO EL TRIGGER.
--PRUEBAS
DROP TRIGGER T_AUTONOMIA;
--LA AUTONOMIA DEL AVION ES SUPERIOR A LA DISTANCIA RECORRIDA MAS DE UN 25%.
UPDATE VUELOS SET DISTANCIA=800 WHERE CODVUELO='IB-5940';
-- EN ESTE UPDATE LA AUTONOMÍA DEL AVIÓN LA DISTANCIA NO ES SUPERIOR
UPDATE VUELOS SET DISTANCIA=5000 WHERE CODVUELO='IB-5940';

-- PROBANDO CON INSERT

--ELIMINAMOS EL ÚLTIMO REGISTRO
DELETE FROM VUELOS WHERE CODVUELO='UX-6013';
-- Este insert la autonomía del avión es superior a la distancia recorrida mas de un 25%. NO TIENE QUE FUNCIONAR
INSERT INTO VUELOS VALUES (
    'UX-6013',
    'PMI',
    'MAD',
    'Air Europa',
    'Jueves',
    TO_DATE('10:15', 'HH24:MI'),
    'EJK000333',
    'HYJ000568',
    7820,
    TO_DATE('01:30','HH24:MI')
);

-- En este insert la autonomía del avión es inferior a la distancia recorrida. Debe de funcionar

INSERT INTO VUELOS VALUES (
    'UX-6013',
    'PMI',
    'MAD',
    'Air Europa',
    'Jueves',
    TO_DATE('10:15', 'HH24:MI'),
    'EJK000333',
    'HYJ000568',
    782,
    TO_DATE('01:30','HH24:MI')
);
